### ISSUE TITLE
Unclear message when getting the efactura messages

### ISSUE THREAD

**Issue by mihaisolomon** [andalisolutions/anaf-php#20]
Hey,

It gives a strange message when you have an empty string from ANAF

![image](https://github.com/andalisolutions/anaf-php/assets/17908506/b3988525-bafb-4edc-aeb2-3e2f579a6759)

Can you put a relevant message, because at first try I understood that something is wrong with my payload.

**Comment by ciungulete** [comment]
Salutare,

Din cate am inteles saptamana aceasta ANAF va actualiza API-ul (sper) si vom putea fi consecventi in afisarea erorilor. Acum, deoarece pe unele endpointuri primesc si XML si json, in functie de eroare, mi-a fost greu sa "le pot ordona".

Cum apare update-ul, fac modificari si in pachet.

Seara buna!

**Comment by ciungulete** [comment]
Astept si PR-uri, daca consideri ca sunt lucruri de imbunatatit :-)

**Comment by mihaisolomon** [comment]
M-am uitat peste pachet, este fain facut. Abia am inceput sa il utilizez pentru o miniaplicatie pentru mine. Momentan nu am simtit nevoia sa modific ceva.
