### ISSUE TITLE
Is there any option to use the test environment when initializing the client

### ISSUE THREAD

**Issue by dnsnx** [andalisolutions/anaf-php#24]
I've got some questions:

Is there any option when initializing the client, to set the environment to "TEST" instead of "PRODUCTION"?
As far as I can see, the URLs are differently.

For testing purposes:
https://webserviceapl.anaf.ro/test/FCTEL/rest/...

For production;
https://webserviceapl.anaf.ro/prod/FCTEL/rest/...

Another question:
In class `Efactura`: What means the parameter `$extern`? When do I set it to `true`?

**Comment by ciungulete** [comment]
Hello,

For testing you can use `factory` with `staging`
```php
$testingClient = Anaf::factory()
    ->withApiKey($apiKey)
    ->staging()
    ->make(); 
```
> In class Efactura: What means the parameter $extern? When do I set it to true?

What I understood from the poorly documented explanations from api + google, `$extern` should only be used if the buyer is from outside Romania and the invoice has VAT. (not sure)
